// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythApi.Common.Database;

#nullable disable

namespace MythApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421120304_AddRegionEntity")]
    partial class AddRegionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MythApi.Common.Database.Models.Alias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("Alias", (string)null);
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.God", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MythologyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MythologyId");

                    b.ToTable("God", (string)null);
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Mythology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Mythology", (string)null);
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Alias", b =>
                {
                    b.HasOne("MythApi.Common.Database.Models.God", null)
                        .WithMany("Aliases")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.God", b =>
                {
                    b.HasOne("MythApi.Common.Database.Models.Mythology", null)
                        .WithMany("Gods")
                        .HasForeignKey("MythologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Mythology", b =>
                {
                    b.HasOne("MythApi.Common.Database.Models.Region", null)
                        .WithMany("Mythologies")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.God", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Mythology", b =>
                {
                    b.Navigation("Gods");
                });

            modelBuilder.Entity("MythApi.Common.Database.Models.Region", b =>
                {
                    b.Navigation("Mythologies");
                });
#pragma warning restore 612, 618
        }
    }
}
